name: Run Checks on Pull Request

on:
  pull_request_target:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test  # Overwritten by Jest anyway.
      BOT_TOKEN: ${{ secrets.PROD_BOT_TOKEN }}
      APPLICATION_ID: ${{ secrets.PROD_APPLICATION_ID }}

      # TODO: There has to be a better way to automate this (for
      # not-so-sensitive variables at least).
      YUNG_KAI_WORLD_GID: ${{ vars.YUNG_KAI_WORLD_GID }}
      BOT_DEV_RID: ${{ vars.BOT_DEV_RID }}
      KAI_RID: ${{ vars.KAI_RID }}
      ALPHA_MOD_RID: ${{ vars.ALPHA_MOD_RID }}
      BABY_MOD_RID: ${{ vars.BABY_MOD_RID }}

      BOT_SPAM_CID: ${{ vars.BOT_SPAM_CID }}
      INTRODUCTIONS_CID: ${{ vars.INTRODUCTIONS_CID }}
      MEDIA_CID: ${{ vars.MEDIA_CID }}
      ARTWORK_CID: ${{ vars.ARTWORK_CID }}
      STINKYS_FRIENDS_CID: ${{ vars.STINKYS_FRIENDS_CID }}
      MUSIC_CHAT_CID: ${{ vars.MUSIC_CHAT_CID }}
      GAMING_CID: ${{ vars.GAMING_CID }}
      COOKING_TIME_CID: ${{ vars.COOKING_TIME_CID }}

      LUKE_UID: ${{ vars.LUKE_UID }}
      KLEE_UID: ${{ vars.KLEE_UID }}
      COFFEE_UID: ${{ vars.COFFEE_UID }}
      CXTIE_UID: ${{ vars.CXTIE_UID }}
      TACO_UID: ${{ vars.TACO_UID }}
      WAV_UID: ${{ vars.WAV_UID }}
      BUNNY_UID: ${{ vars.BUNNY_UID }}
      J_UID: ${{ vars.J_UID }}
      KAI_UID: ${{ vars.KAI_UID }}
      NI_UID: ${{ vars.NI_UID }}
      S_UID: ${{ vars.S_UID }}
      WYS_UID: ${{ vars.WYS_UID }}
      CLIENT_UID: ${{ vars.CLIENT_UID }}
      MUDAE_UID: ${{ vars.MUDAE_UID }}

    steps:
      - name: Check out code on job environment
        uses: actions/checkout@v3

      # I should NOT need to do this, but for SOME reason, actions/checkout
      # doesn't always include the most recent commits...
      - name: Pull changes if missing from actions/checkout
        run: git pull origin main

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test

      - name: Run linter
        run: npm run lint

      - name: Check that TypeScript can compile
        run: npm run build
